# Generated by Django 6.0.1 on 2026-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
