# Generated by Django 6.0.1 on 2026-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment_patient_age_assessment_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='glucose_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='lactate_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='oxidative_stress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pyruvate_level',
            field=models.FloatField(default=0.0),
        ),
    ]
