# Generated by Django 6.0.1 on 2026-02-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assessment_glucose_level_assessment_lactate_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='patient_dob',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='patient_id',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
    ]
