# Generated by Django 6.0.1 on 2026-03-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assessment_patient_dob_assessment_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
    ]
