# Generated by Django 6.0.1 on 2026-03-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assessment_doctor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='culture_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='media_color_change',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ph_deviation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='visual_clarity',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
