# Generated by Django 6.0.1 on 2026-03-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assessment_culture_medium_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysisresult',
            table='doctor_analysisresult',
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='doctor_assessment',
        ),
        migrations.AlterModelTable(
            name='media',
            table='doctor_assessmentmedia',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='doctor_doctorprofile',
        ),
    ]
