# Generated by Django 6.0.1 on 2026-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_analysisresult_table_alter_assessment_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='glucose_level',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='lactate_level',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='oxidative_stress',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='pyruvate_level',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='glucose_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='lactate_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='oxidative_stress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='pyruvate_level',
            field=models.FloatField(default=0.0),
        ),
    ]
