# Generated by Django 6.0.1 on 2026-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_assessment_glucose_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='amino_acids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ammonia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='co2_release',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='oxygen_uptake',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='ph_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='vitamins',
            field=models.IntegerField(default=0),
        ),
    ]
